steps:
  - name: golang:1.27.1-bookworm
    entrypoint: go
    args: ['test', './...']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
options:
  logging: CLOUD_LOGGING_ONLY
